const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function j(url,opt){const r=await fetch(url,opt); if(!r.ok) throw Error(await r.text()); return r.json()}
const roleLabel=r=>String(r||'').replaceAll('_',' ');
function card(p){return `<article class="card clickable" onclick="openProject('${esc(p.id)}')"><div><span class="pill">${esc(p.domain)}</span><span class="pill role">${esc(roleLabel(p.strategic_role))}</span></div><h2>${esc(p.name)}</h2><p>${esc(p.one_liner)}</p><div class="survive"><b>Software kill test</b>${esc(p.substitution_survival)}</div><div class="moat"><b>First moat event</b>${esc(p.first_real_moat_event)}</div><div class="meta"><span>${p.scarce_asset_count} assets</span><span>${esc(p.target_profile||'')}</span></div></article>`}
function ueCard(x){let step=x.next_step; return `<article class="uecard clickable" onclick="openProject('${esc(x.project_id)}')"><div class="uehead"><div><span class="pill">${esc(roleLabel(x.strategic_role))}</span><h3>${esc(x.name)}</h3></div><b class="score">${esc(x.priority_score)}</b></div><div class="target"><small>SCARCE-STATE TARGET</small>${esc(x.scarce_state_target)}</div><p>${esc(x.minimal_live_product)}</p>${step?`<div class="next"><small>NEXT MINIMUM STEP</small><b>${esc(step.action)}</b><span>${esc(step.authority)}-TASK · ${esc(step.acceptance)}</span></div>`:'<div class="next">Minimum path complete — pause and observe.</div>'}<details><summary>NOT NOW (${x.not_now.length})</summary><div class="notnow">${x.not_now.map(v=>`<span>${esc(v)}</span>`).join('')}</div></details></article>`}
function group(title,arr){return `<div class="group"><div class="grouphead"><h3>${esc(title)}</h3><span>${arr.length}</span></div><div class="uegrid">${arr.map(ueCard).join('')}</div></div>`}
function queueCard(x){return `<article class="card"><div><span class="pill role">${esc(x.lane)}</span><span class="pill">${esc(x.world)}</span></div><h2>${esc(x.name)}</h2><p>${esc(x.learning_goal)}</p><div class="moat"><b>Target event</b>${esc(x.first_real_moat_event)}</div><div class="mini"><span>world score ${esc(x.world_score)}</span><span>project ${esc(x.project_priority)}</span><span>${x.resources.map(esc).join(' · ')||'no scarce resource'}</span></div></article>`}
async function boot(){
 let pf=await j('/api/portfolio'); $('#northstar').textContent=pf.northstar; $('#invariant').textContent='HUMAN ENDGAME: '+pf.human_endgame;
 let cps=pf.projects.reduce((a,p)=>a+p.checkpoint_count,0), assets=pf.projects.reduce((a,p)=>a+p.scarce_asset_count,0);
 $('#stats').innerHTML=`<div class="stat"><b>${pf.projects.length}</b><span>campaigns/labs</span></div><div class="stat"><b>${assets}</b><span>declared assets</span></div><div class="stat"><b>${cps}</b><span>behavior gates</span></div>`;
 $('#projects').innerHTML=pf.projects.map(card).join('');
 let order=await j('/api/order'); $('#currentOrder').innerHTML=`<article class="ordercard"><div><span class="eyebrow">CURRENT UNDERENGINEER ORDER</span><h2>${esc(order.project_id)}</h2><p>${esc(order.goal)}</p></div><div><small>NEXT</small><b>${esc(order.next_step?.action||'observe')}</b><small>EXTERNAL WORLD</small><span>${esc(order.recommended_external_world?.id||'none')}</span><small>PULL NOW</small><span>${order.required_components_now.map(esc).join(' · ')}</span></div></article>`;
 let sc=await j('/api/schedule'); $('#liveQueue').innerHTML=sc.live_queue.map(queueCard).join('')||'<p>No live proposals.</p>'; $('#resourceAlloc').innerHTML=Object.entries(sc.resource_allocations).map(([k,v])=>`<article class="card"><span class="pill">resource</span><h2>${esc(k)}</h2><p>allocated units: <b>${esc(v)}</b></p></article>`).join('');
 let lab=await j('/api/selflab'); $('#selfLab').innerHTML=`<article class="widecard"><h3>${esc(lab.thesis)}</h3><div class="flow">${lab.loop.map(x=>`<span>${esc(x)}</span>`).join('<b>→</b>')}</div><p><b>Boundary:</b> ${esc(lab.hard_boundary)}</p><p><b>BreadUp payoff:</b> ${esc(lab.use_for_breadup_customer_product)}</p></article>`;
 let worlds=await j('/api/experiment-worlds'); $('#worldClasses').innerHTML=worlds.classes.map(x=>`<article class="card"><span class="pill role">${esc(x.id)}</span><h2>${esc(x.name)}</h2><p>${esc(x.question)}</p><div class="moat"><b>Graduate on</b>${esc(x.graduation_signal)}</div></article>`).join('');
 let prof=await j('/api/target-profiles'); $('#targetProfiles').innerHTML=prof.profiles.map(x=>`<article class="card"><span class="pill">${esc(x.first_world)}</span><h2>${esc(x.name)}</h2><p>${esc(x.best_for)}</p><div class="mini"><span>feedback ${x.feedback_speed}/5</span><span>barrier ${x.entry_barrier}/5</span><span>scarcity ${x.scarce_state_potential}/5</span></div></article>`).join('');
 let perf=await j('/api/performance'); $('#strategyPerf').innerHTML=perf.families.map(x=>`<article class="card"><span class="pill">${esc(x.promotion_state)}</span><h2>${esc(x.id)}</h2><p>${esc(x.mechanism)}</p><div class="mini"><span>real n=${x.real_attempts}</span><span>success ${x.real_successes}</span><span>posterior ${x.posterior_mean}</span></div></article>`).join('');
 let hd=await j('/api/hdesk'); $('#humanQueue').innerHTML=hd.queue.open.length?hd.queue.open.map(t=>`<article class="widecard"><span class="pill role">${esc(t.kind)}</span><h3>${esc(t.question)}</h3><p>${esc(t.why_human)}</p><div class="mini"><span>${esc(t.project_id||'portfolio')}</span><span>${esc(t.estimated_minutes)} min</span><span>value/min ${esc(t.attention_value_per_minute)}</span></div><p><b>Options:</b> ${(t.options||[]).map(esc).join(' · ')||'bounded answer not supplied'}</p></article>`).join(''):`<article class="widecard empty"><h3>0 open H-tasks</h3><p>Agents should continue autonomously until a valid strategic, physical, identity, spend, relationship or taste bottleneck exists.</p></article>`; $('#humanTypes').innerHTML=hd.templates.allowed_kinds.map(x=>`<article class="card"><h2>${esc(x.id)}</h2><p>${esc(x.when)}</p></article>`).join('');
 let ue=await j('/api/underengineer'); $('#ueGroups').innerHTML=group('1 · Scarce-asset campaigns',ue.asset_campaigns)+group('2 · Hybrid infrastructure / experimental labs',ue.hybrid_infrastructure)+group('3 · Infrastructure — pulled, never self-prioritized',ue.infrastructure);
 let ad=await j('/api/assets'); $('#assetGrid').innerHTML=ad.declared.map(a=>`<article class="card"><div><span class="pill">${esc(a.class)}</span><span class="pill">score ${esc(a.strategic_score)}</span></div><h2>${esc(a.project_name)} · ${esc(a.id)}</h2><p><b>Controlled unit:</b> ${esc(a.unit)}</p><div class="mini"><span>right ${esc(a.our_right)}</span><span>AI moat β ${esc(a.ai_moat_beta)}/5</span></div><div class="moat"><b>Acquire on</b>${esc(a.acquisition_event)}</div><div class="meta"><span>ledger stock: ${esc(a.current_stock)}</span><span>declared ≠ acquired</span></div></article>`).join('');
 let cs=await j('/api/components'); $('#componentGrid').innerHTML=cs.map(c=>`<article class="card"><span class="pill">shared primitive</span><h2>${esc(c.name)}</h2><p>${esc(c.role)}</p><p><b>Boundary:</b> ${esc(c.boundary)}</p>${c.repo?`<a class="repo" href="${esc(c.repo)}">${esc(c.repo)}</a>`:''}</article>`).join('');
 let bs=await j('/api/bottlenecks'); $('#bottleneckGrid').innerHTML=bs.map(b=>`<article class="card"><span class="pill">structural bottleneck</span><h2>${esc(b.name)}</h2><p>${esc(b.statement)}</p><p><b>Current:</b> ${esc(b.current_solution)}</p></article>`).join('')
}
async function openProject(id){
 let p=await j('/api/project?id='+encodeURIComponent(id)), ue=p.underengineer, ex=await j('/api/experiment-worlds?id='+encodeURIComponent(id));
 let assets=(p.scarce_assets||[]).map(a=>`<div class="assetrow"><b>${esc(a.id)}</b><span>${esc(a.class)}</span><span>${esc(a.our_right)}</span><span>β ${esc(a.ai_moat_beta)}/5</span><code>${esc(a.acquisition_event)}</code></div>`).join('')||'<p class="muted">No asset claim from software existence alone.</p>';
 let steps=ue.steps.map(s=>`<div class="cp ue-step"><div class="n">${String(s.ordinal).padStart(2,'0')}</div><div><h3>${esc(s.action)}</h3><p>${esc(s.acceptance)}</p></div><div class="authority">${esc(s.authority)}-TASK</div></div>`).join('');
 let cps=p.checkpoints.map(cp=>`<div class="cp"><div class="n">${String(cp.ordinal).padStart(2,'0')}</div><div><h3>${esc(cp.title)}</h3><p>${esc(cp.implies)}</p><div class="code">min=${esc(cp.validator.minimum_evidence_class||'n/a')} · deps=${esc(cp.depends_on.join(', ')||'none')}</div></div><div class="authority">${esc(cp.authority)}-TASK</div></div>`).join('');
 let wx=ex.ranked_worlds.map(w=>`<div class="assetrow"><b>${esc(w.id)}</b><span>${esc(w.class)}</span><span>score ${esc(w.score)}</span><span>${esc(w.feedback_hours)}h</span><code>${esc(w.canonical_proof_ceiling)}</code></div>`).join('');
 $('#projectDetail').innerHTML=`<div class="detail"><div><span class="pill">${esc(p.domain)}</span><span class="pill role">${esc(roleLabel(p.strategic_role))}</span></div><h2>${esc(p.name)}</h2><p>${esc(p.one_liner)}</p><div class="killtest"><small>SOFTWARE SUBSTITUTION TEST</small><b>${esc(p.software_substitution_test.survival)}</b><p>${esc(p.software_substitution_test.rationale)}</p></div><div class="thesis">${esc(p.core_thesis)}</div><h3>Experiment worlds</h3><div class="assettable">${wx||'<p>none</p>'}</div><h3>Scarce assets</h3><div class="assettable">${assets}</div><div class="ueblock"><span class="eyebrow">UNDERENGINEER/2.0</span><h3>${esc(ue.scarce_state_target)}</h3><p>${esc(ue.minimal_live_product)}</p><div class="moat"><b>First real moat event</b>${esc(ue.first_real_moat_event)}</div>${steps}<details open><summary>Explicitly NOT NOW</summary><div class="notnow">${ue.explicitly_not_now.map(x=>`<span>${esc(x)}</span>`).join('')}</div></details></div><details><summary>Full capability library (${p.checkpoints.length})</summary><div class="checkpoints">${cps}</div></details></div>`;
 $('#projectDialog').showModal()
}
window.openProject=openProject; document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $('#'+b.dataset.view).classList.add('active')}); boot().catch(e=>document.body.innerHTML='<pre>'+esc(e.stack)+'</pre>');
