"""Shared review harness for autobuild attempts. Stdlib only.

Each attempt keeps review/check.py (thin, attempt-specific scope) that calls
into here. Outputs: review/VERDICT.json (machine) + review/NEXT.md (human).
Statuses: PASS / PARTIAL / DEFERRED / FAIL. No FAIL allowed to promote.
"""
import datetime
import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD_ROOT = os.path.dirname(HERE)  # agentcombuild/


def today():
    return datetime.date.today().isoformat()


def run_pytest(attempt_dir):
    """Run the attempt suite. Returns dict(ok, passed, failed, tail)."""
    try:
        p = subprocess.run([sys_exe(), "-m", "pytest", "tests/", "-q"],
                           cwd=attempt_dir, capture_output=True, text=True,
                           timeout=300)
    except Exception as exc:  # noqa: BLE001
        return {"ok": False, "passed": 0, "failed": -1,
                "tail": "harness-error:%s" % exc}
    tail = (p.stdout + p.stderr).strip().splitlines()[-3:]
    passed, failed, ok = 0, 0, p.returncode == 0
    for line in (p.stdout + p.stderr).splitlines():
        if " passed" in line:
            try:
                passed = int(line.split(" passed")[0].split()[-1])
            except ValueError:
                pass
        if " failed" in line:
            try:
                failed = int(line.split(" failed")[0].split()[-1])
            except ValueError:
                pass
    return {"ok": ok, "passed": passed, "failed": failed, "tail": tail}


def sys_exe():
    import sys
    return sys.executable


def check_required_files(attempt_dir, relpaths):
    out = []
    for rel in relpaths:
        full = os.path.join(attempt_dir, rel)
        out.append({"path": rel,
                    "ok": os.path.exists(full)})
    return out


def grep_ban_py(attempt_dir, banned):
    """Banned literal strings must not appear in src/**/*.py. Returns hits.

    Files with 'vendored' in the name are skipped: vendoring external code
    with a provenance header is allowed (never copy schemas silently), and
    the header itself names the source repo.
    """
    hits = []
    src = os.path.join(attempt_dir, "src")
    for root, _, files in os.walk(src):
        for fn in sorted(files):
            if not fn.endswith(".py") or "vendored" in fn:
                continue
            full = os.path.join(root, fn)
            try:
                with open(full, encoding="utf-8") as fh:
                    text = fh.read()
            except OSError:
                continue
            rel = os.path.relpath(full, attempt_dir)
            for pat in banned:
                if pat in text:
                    hits.append({"pattern": pat, "file": rel})
    return hits


def row(cid, status, note=""):
    assert status in ("PASS", "PARTIAL", "DEFERRED", "FAIL")
    return {"id": cid, "status": status, "note": note}


def write_verdict(attempt_dir, attempt, scope, rows, tests, files, bans):
    fails = [r["id"] for r in rows if r["status"] == "FAIL"]
    overall = "FAIL" if (fails or not tests.get("ok")) else (
        "PASS WITH DEBT" if any(r["status"] in ("PARTIAL", "DEFERRED")
                                for r in rows) else "PASS")
    payload = {"attempt": attempt, "date": today(), "scope": scope,
               "overall": overall, "criteria": rows, "tests": tests,
               "files": files, "banned_hits": bans,
               "fails": fails}
    out = os.path.join(attempt_dir, "review", "VERDICT.json")
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
    return payload


def write_next(attempt_dir, attempt, debt_lines, next_scope):
    lines = ["# NEXT after %s (%s)" % (attempt, today()), "",
             "## Carried debt"]
    lines += ["- %s" % d for d in debt_lines] or ["- none"]
    lines += ["", "## Next attempt scope", ""]
    lines += ["- %s" % s for s in next_scope]
    lines += ["", "_Generated by review/check.py. Human edits welcome._", ""]
    with open(os.path.join(attempt_dir, "review", "NEXT.md"), "w",
              encoding="utf-8") as fh:
        fh.write("\n".join(lines))
