#!/usr/bin/env bash
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
mkdir -p validation
LOG=validation/validation.log
: > "$LOG"
PASS=0
FAIL=0
run() {
  local name="$1"; shift
  printf '\n===== %s =====\n' "$name" | tee -a "$LOG"
  printf '$'; printf ' %q' "$@"; printf '\n' | tee -a "$LOG"
  if "$@" >> "$LOG" 2>&1; then
    echo "PASS: $name" | tee -a "$LOG"; PASS=$((PASS+1))
  else
    echo "FAIL: $name" | tee -a "$LOG"; FAIL=$((FAIL+1))
  fi
}
run "compileall" env PYTHONPATH=src python -m compileall -q src tests
run "pytest-full" env PYTHONPATH=src pytest -q
run "pytest-provider-contracts" env PYTHONPATH=src pytest -q tests/test_procurement_registry.py tests/test_qp_procurement.py tests/test_provider_http_adapters.py tests/test_procurement_api_mcp.py
run "editable-install" python -m pip install -e . --no-deps --no-build-isolation -q
run "frontend-js-syntax" node --check src/xmrbot/web/static/app.js
run "import-app" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -c 'from xmrbot.app import app; print("routes", len(app.routes)); assert len(app.routes)>=40'
run "web-route-smoke" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -c 'from fastapi.testclient import TestClient; from xmrbot.app import app; c=TestClient(app); paths=["/","/terminal","/mine","/ask","/blog","/providers","/recipes","/llms.txt","/robots.txt","/sitemap.xml","/v1/site/map","/v1/providers"]; statuses={p:c.get(p).status_code for p in paths}; print(statuses); assert all(v==200 for v in statuses.values())'
run "provider-count-and-sources" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -c 'from xmrbot.procurement.registry import ProviderRegistry; r=ProviderRegistry(); ps=r.all(); print("providers",len(ps)); assert len(ps)==20; assert all(p.source_urls and p.capabilities for p in ps)'
run "all-capabilities-proposable" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -c 'from xmrbot.procurement.registry import ProviderRegistry; r=ProviderRegistry(); n=0; [(r.adapter(p.id).propose(c.name,{"validation":True}),globals().__setitem__("n",globals().get("n",0)+1)) for p in r.all() for c in p.capabilities]; print("capabilities proposed",n); assert n>=40'
run "mcp-stdio-provider-tools" bash -c 'printf "%s\n" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\",\"params\":{}}" | XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -m xmrbot.mcp.stdio | grep -q xmr_procurement_route'
run "mcp-stdio-provider-resources" bash -c 'printf "%s\n" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"resources/list\",\"params\":{}}" | XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -m xmrbot.mcp.stdio | grep -q xmrbot://providers'
run "qp-mutation-rejection" env PYTHONPATH=src python -c 'from xmrbot.procurement.models import ProviderAction,QPGrant; from xmrbot.procurement.policy import evaluate_grant; a=ProviderAction(provider_id="orbitswap",action="create_transaction",payload={"amount":1}); g=QPGrant(id="g",capability="x",approved=True,allowed_providers=["orbitswap"],allowed_actions=["create_transaction"],exact_payload_hash=a.canonical_hash()); b=ProviderAction(provider_id="orbitswap",action="create_transaction",payload={"amount":2}); print(evaluate_grant(b,g).model_dump()); assert not evaluate_grant(b,g).allowed'
run "style-contract" bash -c '! grep -E "(linear-gradient|radial-gradient|backdrop-filter)" src/xmrbot/web/static/styles.css && grep -q -- "--orange:#ff6600" src/xmrbot/web/static/styles.css'
run "forbidden-wallet-export-tools" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -c 'from xmrbot.app import registry; names=set(registry.specs); print(sorted(names)); assert "xmr_export_seed" not in names and "xmr_export_keys" not in names and "wallet.export_seed" not in names and "wallet.export_keys" not in names'
run "no-embedded-real-secrets" bash -c '! grep -R -nE "(-----BEGIN (RSA|OPENSSH|EC) PRIVATE KEY-----|sk_live_[A-Za-z0-9]{12,}|xox[baprs]-[A-Za-z0-9-]{10,})" src docs --exclude-dir=__pycache__'

PYTHONPATH=src pytest --collect-only -q > validation/tests_collected.txt 2>&1 || true
TEST_COUNT=$(awk -F': ' '/tests\/test_/ {s+=$2} END{print s+0}' validation/tests_collected.txt)
{
  echo '# Collected tests'; echo; echo '```text'; cat validation/tests_collected.txt; echo '```';
} > validation/TEST_MANIFEST.md
cat > validation/summary.json <<JSON
{"passed":$PASS,"failed":$FAIL,"pytest_tests":${TEST_COUNT:-0},"providers":20,"log":"validation/validation.log"}
JSON
cat > validation/RESULTS.md <<MD
# Validation results

Generated by \`scripts/validate.sh\` against the final source tree before packaging.

- Passed validation stages: **$PASS**
- Failed validation stages: **$FAIL**
- Collected pytest tests: **${TEST_COUNT:-0}**
- Registered provider adapters/descriptors: **20**
- Native/local API semantics are tested with deterministic \`httpx.MockTransport\` fixtures; no real financial transaction is claimed.
- Manual/read-only/upcoming adapters are validated as proposal/evidence boundaries and are not falsely treated as live transactional APIs.
- Raw commands/stdout/stderr: \`validation/validation.log\`
- Exact pytest collection: \`validation/TEST_MANIFEST.md\`
- Machine-readable summary: \`validation/summary.json\`

The archive should only be treated as passing when \`failed = 0\`.
MD
find src tests docs scripts migrations -type f -print0 | sort -z | xargs -0 sha256sum > validation/SHA256SUMS.txt
cat validation/summary.json
exit "$FAIL"
