#!/usr/bin/env bash
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
mkdir -p validation
LOG=validation/validation.log
: > "$LOG"
PASS=0
FAIL=0
run() {
  local name="$1"; shift
  printf '\n===== %s =====\n' "$name" | tee -a "$LOG"
  printf '$'; printf ' %q' "$@"; printf '\n' | tee -a "$LOG"
  if "$@" >> "$LOG" 2>&1; then
    echo "PASS: $name" | tee -a "$LOG"; PASS=$((PASS+1))
  else
    echo "FAIL: $name" | tee -a "$LOG"; FAIL=$((FAIL+1))
  fi
}
run "compileall" env PYTHONPATH=src python -m compileall -q src tests
run "pytest" env PYTHONPATH=src pytest -q
run "editable-install" python -m pip install -e . --no-deps --no-build-isolation -q
run "frontend-js-syntax" node --check src/xmrbot/web/static/app.js
run "import-app" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -c 'from xmrbot.app import app; print("routes", len(app.routes))'
run "web-route-smoke" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -c 'from fastapi.testclient import TestClient; from xmrbot.app import app; c=TestClient(app); paths=["/","/terminal","/mine","/ask","/blog","/recipes","/llms.txt","/robots.txt","/sitemap.xml","/v1/site/map"]; print({p:c.get(p).status_code for p in paths}); assert all(c.get(p).status_code==200 for p in paths)'
run "cli-network" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -m xmrbot.cli network
run "mcp-stdio-tools" bash -c 'printf "%s\n" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\",\"params\":{}}" | XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -m xmrbot.mcp.stdio | grep -q xmr_blog_draft'
run "mcp-stdio-resources" bash -c 'printf "%s\n" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"resources/list\",\"params\":{}}" | XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -m xmrbot.mcp.stdio | grep -q xmrbot://site'
run "style-contract" bash -c '! grep -E "(linear-gradient|radial-gradient|backdrop-filter)" src/xmrbot/web/static/styles.css && grep -q -- "--orange:#ff6600" src/xmrbot/web/static/styles.css'
run "forbidden-secret-scan" bash -c '! grep -R -nE "(seed_phrase|private_spend_key)[[:space:]]*=" src/xmrbot --exclude-dir=__pycache__'

PYTHONPATH=src pytest --collect-only -q > validation/tests_collected.txt 2>&1 || true
TEST_COUNT=$(awk -F': ' '/tests\/test_/ {s+=$2} END{print s+0}' validation/tests_collected.txt)
{
  echo '# Collected tests'
  echo
  echo '```text'
  cat validation/tests_collected.txt
  echo '```'
} > validation/TEST_MANIFEST.md

cat > validation/summary.json <<JSON
{"passed":$PASS,"failed":$FAIL,"log":"validation/validation.log"}
JSON
cat > validation/RESULTS.md <<MD
# Validation results

Generated by \`scripts/validate.sh\` for the packaged source tree.

- Passed validation stages: **$PASS**
- Failed validation stages: **$FAIL**
- Collected pytest tests: **$TEST_COUNT**
- Full pytest suite is included in the raw log and collected test manifest.
- Raw stdout/stderr: \`validation/validation.log\`
- Machine-readable summary: \`validation/summary.json\`

The archive should only be treated as passing when \`failed = 0\`. The raw log records the commands and outputs used for this build.
MD
cat validation/summary.json
exit "$FAIL"
