#!/usr/bin/env bash
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
mkdir -p validation
LOG=validation/validation.log
: > "$LOG"
PASS=0
FAIL=0
run() {
  local name="$1"; shift
  echo "\n===== $name =====" | tee -a "$LOG"
  echo '$' "$@" | tee -a "$LOG"
  if "$@" >> "$LOG" 2>&1; then
    echo "PASS: $name" | tee -a "$LOG"; PASS=$((PASS+1))
  else
    echo "FAIL: $name" | tee -a "$LOG"; FAIL=$((FAIL+1))
  fi
}
run "compileall" env PYTHONPATH=src python -m compileall -q src
run "pytest" env PYTHONPATH=src pytest -q
run "editable-install" python -m pip install -e . --no-deps --no-build-isolation -q
run "frontend-js-syntax" node --check src/xmrbot/web/static/app.js
run "import-app" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -c 'from xmrbot.app import app; print("routes", len(app.routes))'
run "cli-network" env XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -m xmrbot.cli network
run "mcp-stdio-smoke" bash -c 'printf "%s\n" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\",\"params\":{}}" | XMRBOT_DB_PATH=:memory: PYTHONPATH=src python -m xmrbot.mcp.stdio | grep -q xmr_mining_profitability'
run "forbidden-secret-scan" bash -c '! grep -R -nE "(seed_phrase|private_spend_key)[[:space:]]*=" src/xmrbot --exclude-dir=__pycache__'
cat > validation/summary.json <<JSON
{"passed":$PASS,"failed":$FAIL,"log":"validation/validation.log"}
JSON
cat > validation/RESULTS.md <<MD
# Validation results

This file is generated by \`scripts/validate.sh\`.

- Passed validation stages: **$PASS**
- Failed validation stages: **$FAIL**
- Raw stdout/stderr: \`validation/validation.log\`
- Machine-readable summary: \`validation/summary.json\`

The archive should only be treated as passing when failed = 0. The raw log contains the exact commands and tool output from the packaged build.
MD
cat validation/summary.json
exit "$FAIL"
